### ISSUE TITLE
Update rubygems.org with latest exclude feature

### ISSUE THREAD

**Issue by Stromweld** [Pryz/yaml-lint#16]
Would you be able to push an update to rubygems.org with the latest exclude feature included please? I use this gem in my automated linting processes and have run into a yaml file that fails but is correct yaml syntax and simply want to exclude it from linting with all the other yaml files in a directory.

Thanks

**Comment by aerostitch** [comment]
Sorry for the delay @Stromweld .
0.0.10 has just been released to rubygems.org
