### ISSUE TITLE
Errors are printed on stdout

### ISSUE THREAD

**Issue by wilbertom** [Pryz/yaml-lint#18]
It would be great if the errors could be printed to stderr, then we can pipe stdout to `/dev/null` in things like git hooks. If you would welcome this change I would be glad to make it.

**Comment by aerostitch** [comment]
Hi @wilbertom,

That's doable, but I'm wondering if your use case wouldn't already be covered by the existing options already like:
* `-q`, `--quiet`; run quiet. Only log failing files
* `-Q`, `--very-quiet`: run more quiet. Return code is the number of failed files.

If not, yes the PR are welcome! :)

**Comment by wilbertom** [comment]
Hey @aerostitch the `--quiet` flag does cover my need. Thank you, sorry I missed it.
