### ISSUE TITLE
undefined method 'unsafe_load' for Psych:Module in v0.1.0

### ISSUE THREAD

**Issue by andybotting** [Pryz/yaml-lint#24]
We just started pulling in the new version on our CI system and immediately hit the error:

`error: undefined method 'unsafe_load' for Psych:Module`

Obviously related to commit d229e1fcf61cc109073b7cfc43c92d40df3336c9

We're running on Ubuntu Jammy `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`.

**Comment by andybotting** [comment]
I think this is related to a breaking change in Psych v4. 

https://github.com/ruby/psych/issues/533

We're using the Ubuntu packaged version, which is v3.3, so that's possibly the issue.

**Comment by aerostitch** [comment]
I think #25 should address that issue.

**Comment by aerostitch** [comment]
Can you retry witn 0.1.1 that I just pushed please?

**Comment by andybotting** [comment]
I'll confirm shortly

**Comment by andybotting** [comment]
Works for me. Thanks very much for your quick response :tada:
