### ISSUE TITLE
Current dir not parsed correctly

### ISSUE THREAD

**Issue by arioch** [Pryz/yaml-lint#3]
```
☃  yaml-lint .
Checking the content of ["."]
Done.
☃  echo $?
0
```

```
☃  yaml-lint ./test.yaml
Checking the content of ["./test.yaml"]
File : ./test.yaml, error: (./test.yaml): block sequence entries are not allowed in this context at line 1 column 6
Done.
☃  echo $?
1
```

**Comment by MattBurgess** [comment]
This is because of https://github.com/Pryz/yaml-lint/blob/master/lib/yaml-lint.rb#L56.  If I comment that line out, I see the expected behaviour.  I've no idea why it's treating '.' and '.'. specially; they're as valid a directory as any other!
